apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-gitops
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/deep-shukla-31/devops-gitops-platform.git
    targetRevision: main
    path: helm/fastapi-app
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
