apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/deep-shukla-31/devops-gitops-platform
    targetRevision: main
    path: helm/fastapi-app
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
