apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-app.fullname" . }}
  labels:
    app: {{ include "fastapi-app.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "fastapi-app.name" . }}
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http


