replicaCount: 2

image:
  repository: ghcr.io/deep-shukla-31/devops-gitops-platform/fastapi

  tag: 09a54427c6533f131bbdd07db50d6ed4fdaa10ee

  tag: 09a54427c6533f131bbdd07db50d6ed4fdaa10ee
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetport: 8000
resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"
